version: '3'
services:
    app:
        build: .
        volumes:
            - ./src:/go/app
        ports:
            - "8080:8080"
        environment:
            DB_HOST: db
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        depends_on:
            - db

    db:
        container_name: db
        build:
            context: ./db
        volumes:
            - ./db/mysql_data:/var/lib/mysql
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
