version: '3.4'
services:
  app:
    links:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
      target: builder
    command: "air -c .air.toml"
    volumes:
        - ./src:/go/app
    ports:
        - "8080:8080"
    depends_on:
      - db

  db:
    container_name: db
    build:
      context: ./db
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
